services:
  - type: web
    name: senkusolutions
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:dKkoazZb7U1PK0OOnma7gUzJTXf8XpgV/E4NRlT3Q8g=
      - key: DB_CONNECTION
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: senku-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: senku-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: senku-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: senku-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: senku-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_DRIVER
        value: database

databases:
  - name: senku-db
    plan: free
